#!/bin/bash

#SBATCH --job-name=LLMFACTORY_JOB    # create a short name for your job
#SBATCH --nodes=5
#SBATCH --ntasks-per-node=1      # total number of tasks per node
#SBATCH --gres=gpu:8            # number of gpus per node
#SBATCH --cpus-per-task=1        # cpu-cores per task (>1 if multi-threaded tasks)

##### Number of total processes 
echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX "
echo "Nodelist:= " $SLURM_JOB_NODELIST
echo "Number of nodes:= " $SLURM_JOB_NUM_NODES
echo "Ntasks per node:= "  $SLURM_NTASKS_PER_NODE
echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX "

# If you want to load things from your .bashrc profile, e.g. cuda drivers, singularity etc 
source ~/.bashrc

echo "Run started at:- "
date

# Actual run of script 
srun /cm/shared/data/LLaMA-Factory/d_launch_training.sh



echo ""
echo "################################################################"
echo "@@@@@@@@@@@@@@@@@@ Run completed at:- @@@@@@@@@@@@@@@@@@@@@@@@@"
date
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "################################################################"


