#!/bin/bash
###
#SBATCH --job-name=llmfactory
#SBATCH --nodes=1
#SBATCH --gpus-per-node=4
#SBATCH --output="//project/ibi-staff/llmfactory/logs/%x-%j.out"
#SBATCH -p priority
##SBATCH --exclusive

export NCCL_DEBUG=INFO
export NCCL_DEBUG_SUBSYS=INIT,GRAPH

# setup
#export TRANSFORMERS_OFFLINE=0
#export TORCH_NCCL_AVOID_RECORD_STREAMS=1
#export NCCL_NVLS_ENABLE=0
#export NCCL_ASYNC_ERROR_HANDLING=1

# Additional setting for DGX Cloud
#export OMPI_MCA_coll_hcoll_enable=0
#export UCX_TLS=tcp
#export UCX_NET_DEVICES=eth0
#export CUDA_DEVICE_ORDER=PCI_BUS_ID
#export NCCL_SOCKET_IFNAME=eth0
#export NCCL_IB_PCI_RELAXED_ORDERING=1
#export NCCL_DEBUG=INFO
#export NCCL_PROTO=LL,LL128,Simple
#export NCCL_ALGO=Tree,Ring,CollnetDirect,CollnetChain,NVLS
#export MELLANOX_VISIBLE_DEVICES=all
#export PMIX_MCA_gds=hash
#export PMIX_MCA_psec=native

# configure network
export MASTER_ADDR=$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)
export MASTER_PORT=$((${SLURM_JOB_ID} % 16384 + 49152))
export GPUS_PER_NODE=$SLURM_GPUS_PER_NODE
export NNODES=$SLURM_NNODES
#export RANK=${PMIX_RANK}
export NUM_NODES=${NNODES}
export NUM_GPU=${GPUS_PER_NODE}

#export NUM_PROCESSES=$(expr $NNODES \* $GPUS_PER_NODE)
#export RANK=${SLURM_PROCID}
#export LOCAL_RANK=${SLURM_LOCALID}

echo "MASTER_ADDR: $MASTER_ADDR"
echo "MASTER_PORT: $MASTER_PORT"
echo "GPUS_PER_NODE: $GPUS_PER_NODE"
echo "NNODES: $NNODES"
#echo "NUM_PROCESSES: $NUM_PROCESSES"
#echo "RANK: $RANK"
#echo "LOCAL_RANK: $LOCAL_RANK"

#export NUM_NODES=2
#export NUM_GPU=8

export NVIDIA_VISIBLE_DEVICES=all
export NVIDIA_DRIVER_CAPABILITIES=compute,utility

export MPI_TYPE=pmix

export FORCE_TORCHRUN=1


# Log the assigned nodes
echo "Using nodes: $SLURM_JOB_NODELIST"

#/bin/bash -c set > /project/ibi-staff/llmfactory/set.log

export CLEARML_CONFIG_FILE=/root/clearml.conf

export CONTAINER=/project/ibi-staff/llmfactory/container/llmfactory.sqfs
#export CONTAINER=/home/wvlo222/containers/llmfactory_copy.sqfs

export MOUNTS=/project/ibi-staff/llmfactory/custom_data:/app/custom_data,/project/ibi-staff/llmfactory/working_dir:/app/working_dir,/project/ibi-staff/llmfactory/config/clearml.conf:/root/clearml.conf,/project/ibi-staff/llmfactory/config/hosts:/etc/hosts,/project/ibi-staff/llmfactory/models:/app/basemodels

#srun --mpi=$MPI_TYPE --container-image /project/ibi-staff/llmfactory/container/llmfactory.sqfs --container-mounts=/project/ibi-staff/llmfactory/config/clearml.conf:/root/clearml.conf,/project/ibi-staff/llmfactory/config/hosts:/etc/hosts,/project/ibi-staff/llmfactory/models:/models ls -la /root

#srun --container-image=$CONTAINER --no-container-mount-home --container-mounts=$MOUNTS /app/execute_job.sh $1
srun --mpi=$MPI_TYPE --container-image=$CONTAINER --no-container-mount-home --container-mounts=$MOUNTS /app/execute_job.sh $1