deepspeed_config:
  deepspeed_multinode_launcher: pdsh #standard #pdsh
  deepspeed_config_file: /workspace/config/deep_speed_zero2.json
  zero3_init_flag: true
distributed_type: DEEPSPEED
downcast_bf16: 'no'
main_training_function: main
num_processes: 40
num_machines: 5
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false